### ISSUE TITLE
Status update 

### ISSUE THREAD

**Issue by ghost** [OR-WindPredicition/WindPredictionAPI#4]
Ask Eric for an update for the Cloud controller

**Comment by ghost** [comment]
Asked for an update

**Comment by Niekvandam** [comment]
ISSD has responded to the request, it turns out that ISSD did not yet order the wind turbine which is now temporarily out of stock. This means that we have to wait until the item is back in stock before we can get started with the installation of the wind turbine. For now, we will have to research alternative ways to gather the data, which probably means going back to the anemometer
